name: CMake Build with GCC

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build-with-gcc:
        runs-on: windows-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Setup mingw64
              run: |
                  Invoke-WebRequest https://github.com/brechtsanders/winlibs_mingw/releases/download/14.2.0posix-19.1.1-12.0.0-ucrt-r2/winlibs-x86_64-posix-seh-gcc-14.2.0-mingw-w64ucrt-12.0.0-r2.zip -OutFile C:\mingw64.zip
                  Expand-Archive -Force C:\mingw64.zip -DestinationPath C:\
              shell: pwsh

            - name: Configure
              run: |
                  mkdir build
                  cd build
                  cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release ..

            - name: Build
              run: |
                  cd build
                  cmake --build . --config Release
